def generate_exception():
    a=10
    b=0
    res=a/b  
    print("Result:", res)
generate_exception()
